version: '2.1'
volumes:
  data:
services:
  radvd:
    build: ./radvd
    volumes:
      - 'data:/data'
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
